"""End-to-end regime detection through the real pipeline and a real Redis.

The unit tests prove the maths. These prove the *wiring*: that a transition
computed in ``fx_core.alerts`` actually reaches the durable WAL, the Pub/Sub
channel and a promoted standby - and that the hysteresis which survives noise in
a pure-Python loop still survives it after passing through tick aggregation,
bar sealing and a network hop.

Nothing here is mocked. Mocking Redis would mean mocking the exact semantics
under test - stream durability, key TTLs, snapshot round-tripping - which is to
say it would prove nothing at all.

WHY THE THRESHOLDS ARE 1.2/0.3 AND NOT 3.0/1.5
----------------------------------------------
A pure sinusoid caps its own z-score. The baseline's dispersion is *generated by
the sine itself*, so for a sine of log-amplitude A plus noise s, the z at the
crest tends to

    A / sqrt(A^2/2 + s^2)

which is bounded near sqrt(2) no matter how large A gets. That is a property of
the test signal, not of the detector: real volatility regimes are episodic, so a
crisis stands far above a baseline built from calm. Tuning the thresholds to the
signal's crest factor is the honest move; cranking the amplitude until 3.0 fires
would just be misreading why it did not.

The production defaults (3.0 / 1.5) are exercised against realistic episodic
data in ``tests/unit/test_regime_detection.py``.
"""

from __future__ import annotations

import asyncio
import contextlib
import json
import math
from datetime import datetime, timedelta
from itertools import pairwise
from typing import Any

import pytest
import redis.asyncio as aioredis
from fx_core import keys
from fx_core.alerts import DetectorConfig, Regime, TriggerConfig, VolatilityBaseline
from fx_core.alerts.baseline import lambda_for_halflife
from fx_ingestor.pipeline import IngestPipeline

from tests.chaos.sine_feed import SineVolatilityFeed, macro_phase

pytestmark = [pytest.mark.chaos, pytest.mark.integration, pytest.mark.anyio]

SYMBOL = "EURUSD"
PERIOD = 180
WARMUP = 150
CYCLES = 4
MINUTES = WARMUP + CYCLES * PERIOD

# Baseline half-life must be long relative to the macro cycle, or the reference
# tracks the very signal it is supposed to be a reference FOR.
BASELINE_HALFLIFE = 600

TRIGGER = TriggerConfig(
    enter_z=1.2,
    exit_z=0.3,
    min_confirm_samples=5,
    confirm_for=timedelta(minutes=5),
    sample_timeout=timedelta(minutes=30),
    cooldown=timedelta(minutes=20),
    thaw_after=timedelta(hours=48),  # beyond the run: isolate hysteresis from thawing
)
DETECTOR = DetectorConfig(session_warmup=timedelta(0), rearm_bars=2)


def build_pipeline(redis: aioredis.Redis, symbols: list[str] | None = None) -> IngestPipeline:
    pipeline = IngestPipeline(
        redis,
        symbols or [SYMBOL],
        bucket_seconds=60,
        detector_config=DETECTOR,
        trigger_config=TRIGGER,
    )
    for symbol in pipeline.symbols:
        state = pipeline.state_for(symbol)
        state.detector.baseline = VolatilityBaseline(
            lam=lambda_for_halflife(BASELINE_HALFLIFE), min_samples=30
        )
        # The chaos clock is a fixed Wednesday; without injecting this the suite
        # would silently stop testing anything every weekend.
        state.detector.market_is_open = lambda _ts: True
    return pipeline


async def drive(
    pipeline: IngestPipeline, feed: SineVolatilityFeed, minutes: int
) -> list[dict[str, Any]]:
    """Push every tick through the real pipeline. Returns the transitions logged."""
    for tick in feed.ticks(minutes):
        await pipeline.handle(tick)
    return []


async def read_alert_wal(redis: aioredis.Redis) -> list[dict[str, str]]:
    entries = await redis.xrange(keys.STREAM_ALERTS)
    return [fields for _entry_id, fields in entries]


class ChannelCollector:
    """Subscribes to ch:alerts:* and records everything that arrives."""

    def __init__(self, redis: aioredis.Redis) -> None:
        self._redis = redis
        self.received: list[dict[str, Any]] = []
        self._pubsub: aioredis.client.PubSub | None = None
        self._task: asyncio.Task[None] | None = None

    async def _listen(self) -> None:
        assert self._pubsub is not None
        async for message in self._pubsub.listen():
            if message and message.get("type") in ("message", "pmessage"):
                self.received.append(json.loads(message["data"]))

    async def __aenter__(self) -> ChannelCollector:
        self._pubsub = self._redis.pubsub(ignore_subscribe_messages=True)
        await self._pubsub.psubscribe(keys.channel_alert("*"))
        self._task = asyncio.create_task(self._listen(), name="alert-collector")
        await asyncio.sleep(0.1)  # let the subscription establish before any publish
        return self

    async def __aexit__(self, *exc: object) -> None:
        await asyncio.sleep(0.2)  # drain anything still in flight
        if self._task is not None:
            self._task.cancel()
            with contextlib.suppress(asyncio.CancelledError):
                await self._task
        if self._pubsub is not None:
            await self._pubsub.aclose()


# ===================================================== the full pipeline ====
class TestRegimeDetectionEndToEnd:
    async def test_transitions_reach_both_the_wal_and_the_channel(
        self, redis: aioredis.Redis
    ) -> None:
        """Durability and immediacy are different requirements; we need both.

        Pub/Sub gets the alert on screen in milliseconds and loses it if nobody
        is listening. The stream never loses it but is no use to a browser. They
        are written in the same MULTI, so a transition that is recorded is also
        broadcast - there is no state where one exists without the other.
        """
        pipeline = build_pipeline(redis)
        feed = SineVolatilityFeed(symbol=SYMBOL, period_minutes=PERIOD, warmup_minutes=WARMUP)

        async with ChannelCollector(redis) as collector:
            await drive(pipeline, feed, MINUTES)

        wal = await read_alert_wal(redis)
        assert wal, "no transitions reached the durable WAL"
        assert len(collector.received) == len(wal), (
            f"WAL has {len(wal)} transitions but the channel carried "
            f"{len(collector.received)} - the two paths disagree"
        )

        for entry, published in zip(wal, collector.received, strict=True):
            assert entry["s"] == published["s"]
            assert int(entry["seq"]) == published["seq"]
            assert entry["new_regime"] == published["new_regime"]
            assert entry["cause"] == published["cause"]

    async def test_hysteresis_survives_the_noise_end_to_end(self, redis: aioredis.Redis) -> None:
        """One escalation per macro cycle, and none from the noise in between.

        The signal carries log-noise at a third of the macro amplitude, so a
        single-threshold detector on the same z series crosses dozens of times.
        """
        pipeline = build_pipeline(redis)
        feed = SineVolatilityFeed(symbol=SYMBOL, period_minutes=PERIOD, warmup_minutes=WARMUP)
        await drive(pipeline, feed, MINUTES)

        wal = await read_alert_wal(redis)
        escalations = [e for e in wal if e["new_regime"] == "stressed"]

        print(f"\n  {CYCLES} macro cycles, log-amplitude {feed.amplitude}, noise {feed.noise_sd}")
        print(f"  escalations: {len(escalations)}   total transitions: {len(wal)}")

        assert len(escalations) == CYCLES, (
            f"expected exactly {CYCLES} escalations (one per cycle), got {len(escalations)}"
        )

        # Every escalation must land on the RISE into a crest, never in a trough.
        # Confirmation costs five bars, so it fires before the peak at phase 0.25.
        for entry in escalations:
            minute = int((datetime.fromisoformat(entry["ts"]) - feed.start).total_seconds() // 60)
            phase = macro_phase(minute, WARMUP, PERIOD)
            print(f"    escalated at phase {phase:.2f} (crest is 0.25)")
            assert 0.0 < phase < 0.30, f"escalated at phase {phase:.2f}, nowhere near a crest"

    async def test_alternation_and_seq_invariants_hold_on_the_wal(
        self, redis: aioredis.Redis
    ) -> None:
        """The invariant the database view checks, asserted at the source.

        If it holds here but not in Postgres, the bug is in persistence. If it
        fails here, the bug is in the state machine. Testing it at both ends is
        what makes the eventual failure diagnosable.
        """
        pipeline = build_pipeline(redis)
        await drive(
            pipeline,
            SineVolatilityFeed(symbol=SYMBOL, period_minutes=PERIOD, warmup_minutes=WARMUP),
            MINUTES,
        )

        wal = await read_alert_wal(redis)
        assert len(wal) >= 2 * CYCLES - 1

        assert [int(e["seq"]) for e in wal] == list(range(1, len(wal) + 1))
        for previous, current in pairwise(wal):
            assert previous["new_regime"] == current["old_regime"], "alternation broken"
            assert current["new_regime"] != previous["new_regime"]
        assert wal[0]["old_regime"] == "normal"

    async def test_wal_entries_carry_every_column_the_schema_requires(
        self, redis: aioredis.Redis
    ) -> None:
        """A field missing here becomes a NOT NULL violation in the worker."""
        pipeline = build_pipeline(redis)
        await drive(
            pipeline,
            SineVolatilityFeed(symbol=SYMBOL, period_minutes=PERIOD, warmup_minutes=WARMUP),
            MINUTES,
        )

        required = {
            "s",
            "seq",
            "ts",
            "old_regime",
            "new_regime",
            "trigger_value",
            "threshold_value",
            "sigma",
            "cause",
            "reason",
        }
        for entry in await read_alert_wal(redis):
            assert required <= set(entry), f"missing {required - set(entry)}"
            assert entry["cause"] in {"threshold", "baseline_thaw", "observation_lost"}
            assert entry["old_regime"] != entry["new_regime"]
            assert math.isfinite(float(entry["trigger_value"]))


# ============================================================== failover ====
class TestFailoverRehydration:
    """The duplicate-alert bug, and the state that prevents it."""

    async def _drive_until_stressed(
        self, redis: aioredis.Redis, feed: SineVolatilityFeed
    ) -> tuple[IngestPipeline, int]:
        pipeline = build_pipeline(redis)
        minute = 0
        ticks = feed.ticks(MINUTES)
        for tick in ticks:
            await pipeline.handle(tick)
            minute = int((tick.ts_event - feed.start).total_seconds() // 60)
            if pipeline.state_for(SYMBOL).detector.regime is Regime.STRESSED:
                break
        assert pipeline.state_for(SYMBOL).detector.regime is Regime.STRESSED, (
            "feed never escalated, so there is no failover to test"
        )
        return pipeline, minute

    async def test_promoted_standby_rehydrates_the_regime(self, redis: aioredis.Redis) -> None:
        feed = SineVolatilityFeed(symbol=SYMBOL, period_minutes=PERIOD, warmup_minutes=WARMUP)
        leader, _ = await self._drive_until_stressed(redis, feed)
        original = leader.state_for(SYMBOL).detector

        # ...the leader's container is killed. A standby wins the lease.
        standby = build_pipeline(redis)
        assert standby.state_for(SYMBOL).detector.regime is Regime.NORMAL, "not a cold start"

        restored = await standby.restore_detectors()
        revived = standby.state_for(SYMBOL).detector

        assert restored == 1
        assert revived.regime is Regime.STRESSED
        assert revived.trigger.seq == original.trigger.seq
        # The baseline came back too - otherwise the standby would be blind for
        # min_samples bars while it relearned what normal looks like.
        assert revived.baseline.n == original.baseline.n
        assert revived.baseline.zscore(3e-4) == pytest.approx(original.baseline.zscore(3e-4))

    async def test_a_cold_standby_goes_silent_mid_crisis(self, redis: aioredis.Redis) -> None:
        """The control arm, and the reason rehydration exists.

        We expected a cold standby to re-fire the escalation. Measured, it does
        something worse: it re-baselines on the ELEVATED data, concludes that is
        normal, and reports NORMAL for the rest of the event. It then never emits
        the clear either - so the database's last stored row for this symbol says
        'stressed' forever, waiting for a matching transition that no longer has
        a state machine to produce it.

        A duplicate alert is noisy. This is silent, and it corrupts the
        alternation invariant at the persistence layer, which is the failure you
        find weeks later while reading a chart.
        """
        feed = SineVolatilityFeed(symbol=SYMBOL, period_minutes=PERIOD, warmup_minutes=WARMUP)
        leader, resume_minute = await self._drive_until_stressed(redis, feed)
        assert leader.state_for(SYMBOL).detector.regime is Regime.STRESSED

        tail = self._tail(feed, resume_minute)
        await redis.delete(keys.STREAM_ALERTS)

        cold = build_pipeline(redis)  # NOT rehydrated
        for tick in tail:
            await cold.handle(tick)

        detector = cold.state_for(SYMBOL).detector
        wal = await read_alert_wal(redis)
        print(f"\n  cold standby after {len(tail) // 8} min of an ongoing crisis:")
        print(f"    regime={detector.regime}  seq={detector.trigger.seq}  transitions={len(wal)}")

        assert detector.regime is Regime.NORMAL, "the control arm no longer reproduces the bug"
        assert wal == [], "cold standby emitted transitions it had no business emitting"
        # seq restarting from zero is the collision hazard the alert persister
        # detects by comparing timestamps - see fx_worker.alerts.
        assert detector.trigger.seq == 0

    async def test_rehydrated_standby_continues_the_event_seamlessly(
        self, redis: aioredis.Redis
    ) -> None:
        """The fix, against the same tail of the same feed.

        The rehydrated standby knows it is mid-event, so it emits no duplicate
        escalation - and crucially it DOES emit the clear when the crest passes,
        with ``seq`` continuing from the leader's rather than restarting. The
        stored history stays a single unbroken alternating chain across a
        failover the database never sees.
        """
        feed = SineVolatilityFeed(symbol=SYMBOL, period_minutes=PERIOD, warmup_minutes=WARMUP)
        leader, resume_minute = await self._drive_until_stressed(redis, feed)
        leader_seq = leader.state_for(SYMBOL).detector.trigger.seq

        tail = self._tail(feed, resume_minute)
        await redis.delete(keys.STREAM_ALERTS)

        standby = build_pipeline(redis)
        assert await standby.restore_detectors() == 1
        assert standby.state_for(SYMBOL).detector.regime is Regime.STRESSED
        for tick in tail:
            await standby.handle(tick)

        wal = await read_alert_wal(redis)
        escalations = [e for e in wal if e["new_regime"] == "stressed"]
        clears = [e for e in wal if e["new_regime"] == "normal"]
        print(f"\n  rehydrated standby: {len(escalations)} escalations, {len(clears)} clears")
        print(f"    leader seq was {leader_seq}; standby emitted {[e['seq'] for e in wal]}")

        assert escalations == [], "rehydrated standby emitted a duplicate escalation"
        assert len(clears) == 1, "the clear for the leader's escalation never arrived"
        # The chain continues rather than restarting: this is what keeps
        # (symbol, seq) unique across a failover.
        assert int(clears[0]["seq"]) == leader_seq + 1
        assert clears[0]["old_regime"] == "stressed"

    @staticmethod
    def _tail(feed: SineVolatilityFeed, resume_minute: int) -> list[Any]:
        """The ticks the leader never got to, replayed from the identical feed."""
        cutoff = feed.start + timedelta(minutes=resume_minute, seconds=59)
        continuation = SineVolatilityFeed(
            symbol=SYMBOL,
            period_minutes=PERIOD,
            warmup_minutes=WARMUP,
            seed=feed.seed,
            start=feed.start,
        )
        return [t for t in continuation.ticks(resume_minute + 140) if t.ts_event > cutoff]

    async def test_detector_snapshot_is_durable_not_ttled(self, redis: aioredis.Redis) -> None:
        """The diurnal profile takes days to learn; a TTL would silently discard it.

        This is the same invariant the Redis eviction policy relies on -
        no TTL means durable, and ``volatile-lru`` cannot evict it.
        """
        pipeline = build_pipeline(redis)
        await drive(
            pipeline,
            SineVolatilityFeed(symbol=SYMBOL, period_minutes=PERIOD, warmup_minutes=WARMUP),
            WARMUP + 30,
        )

        assert await redis.exists(keys.regime_state(SYMBOL))
        assert await redis.ttl(keys.regime_state(SYMBOL)) == -1, "detector state must not expire"
        assert keys.STREAM_ALERTS in keys.DURABLE_KEYS

    async def test_a_corrupt_snapshot_degrades_instead_of_crashing(
        self, redis: aioredis.Redis
    ) -> None:
        """Refusing to start because a cache key is malformed turns a degraded
        feed into no feed. Start cold, log it, carry on."""
        await redis.set(keys.regime_state(SYMBOL), "{not json")
        pipeline = build_pipeline(redis)

        assert await pipeline.restore_detectors() == 0
        assert pipeline.state_for(SYMBOL).detector.regime is Regime.NORMAL


# =================================================== gates, in the pipeline =
class TestPipelineGates:
    @staticmethod
    def _spike(feed: SineVolatilityFeed, after_minutes: int) -> SineVolatilityFeed:
        return SineVolatilityFeed(
            symbol=SYMBOL,
            base_sigma=5e-3,  # fifty times normal
            amplitude=0.0,
            noise_sd=0.0,
            warmup_minutes=0,
            period_minutes=PERIOD,
            start=feed.start + timedelta(minutes=after_minutes),
        )

    async def test_a_stale_feed_never_escalates(self, redis: aioredis.Redis) -> None:
        """A frozen price reads as exactly zero volatility.

        Ungated, a dead connection produces "volatility collapsed!" - the most
        embarrassing false positive available to a market dashboard. Kept under
        the observation timeout here, so this tests the gate alone.
        """
        pipeline = build_pipeline(redis)
        feed = SineVolatilityFeed(symbol=SYMBOL, period_minutes=PERIOD, warmup_minutes=WARMUP)
        await drive(pipeline, feed, WARMUP + 40)

        pipeline.set_feed_stale(True)
        before = len(await read_alert_wal(redis))
        for tick in self._spike(feed, WARMUP + 40).ticks(20):
            await pipeline.handle(tick)

        assert len(await read_alert_wal(redis)) == before, "alerted while the feed was stale"
        assert not pipeline.state_for(SYMBOL).detector.armed

    async def test_prolonged_blindness_stops_asserting_a_regime(
        self, redis: aioredis.Redis
    ) -> None:
        """Holding a regime through an outage is right; holding it forever is not.

        This test originally asserted "no transitions at all while stale" and
        failed - correctly. Past ``observation_timeout`` the trigger stops
        claiming a regime it has no evidence for and commits a clear tagged
        ``observation_lost``, which is a different claim from "the market calmed
        down" and is stored as such.
        """
        pipeline = build_pipeline(redis)
        feed = SineVolatilityFeed(symbol=SYMBOL, period_minutes=PERIOD, warmup_minutes=WARMUP)
        leader_minutes = WARMUP + PERIOD
        for tick in feed.ticks(leader_minutes):
            await pipeline.handle(tick)
            if pipeline.state_for(SYMBOL).detector.regime is Regime.STRESSED:
                break
        assert pipeline.state_for(SYMBOL).detector.regime is Regime.STRESSED

        await redis.delete(keys.STREAM_ALERTS)
        pipeline.set_feed_stale(True)
        for tick in self._spike(feed, WARMUP + PERIOD).ticks(45):  # past the 30 min timeout
            await pipeline.handle(tick)

        wal = await read_alert_wal(redis)
        assert [e["new_regime"] for e in wal] == ["normal"]
        assert wal[0]["cause"] == "observation_lost"
        assert wal[0]["trigger_value"] == "", "there is no z-score when nothing is observable"

    async def test_a_gap_bar_does_not_fire(self, redis: aioredis.Redis) -> None:
        """The Sunday-reopen artefact, reproduced without waiting for Sunday.

        A bar whose return spans a session break carries a whole weekend of
        repricing. Ungated it scores z ~ 11 and fires every week, on schedule.
        """
        pipeline = build_pipeline(redis)
        feed = SineVolatilityFeed(symbol=SYMBOL, period_minutes=PERIOD, warmup_minutes=WARMUP)
        await drive(pipeline, feed, WARMUP + 40)
        before = len(await read_alert_wal(redis))

        # A ten minute hole: comfortably past GAP_BAR_MULTIPLE, comfortably
        # short of observation_timeout. Isolating one mechanism per test matters
        # here - a two hour hole ALSO trips the observation timeout, and the test
        # would then pass for a reason it was not written to check.
        gap = SineVolatilityFeed(
            symbol=SYMBOL,
            base_sigma=4e-3,
            amplitude=0.0,
            noise_sd=0.0,
            warmup_minutes=0,
            period_minutes=PERIOD,
            start=feed.start + timedelta(minutes=WARMUP + 40 + 10),
        )
        for tick in gap.ticks(6):
            await pipeline.handle(tick)

        assert len(await read_alert_wal(redis)) == before, "the gap bar fired an alert"
